# Generated by Django 3.1.1 on 2022-01-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=255)),
                ('vehicle_description', models.TextField()),
                ('vehicle_type', models.CharField(max_length=255)),
                ('vehicle_price', models.IntegerField()),
                ('vehicle_image', models.ImageField(upload_to='vehicles/images')),
            ],
        ),
    ]
