# Generated by Django 3.1.1 on 2022-03-19 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_usedvehicle_dateposted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedvehicle',
            name='datePosted',
            field=models.DateField(default=datetime.date(2022, 3, 19)),
        ),
    ]
