# Generated by Django 3.1.1 on 2022-03-19 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_auto_20220319_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedvehicle',
            name='datePosted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
