# Generated by Django 3.1.1 on 2022-03-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_usedvehicle_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedvehicle',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
