# Generated by Django 4.0.4 on 2022-05-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_auto_20220319_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('rc', models.FileField(null=True, upload_to='')),
                ('puc', models.FileField(null=True, upload_to='')),
                ('insurance', models.FileField(null=True, upload_to='')),
                ('invoice', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='usedvehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
