# Generated by Django 4.0.4 on 2022-05-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_alter_documents_insurance_alter_documents_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='insurance',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='invoice',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='puc',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='rc',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
