# Generated by Django 4.0.4 on 2022-05-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_alter_documents_insurance_alter_documents_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='model_name',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
